//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiVideojuegos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Juego
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string plataforma { get; set; }
        public int anio { get; set; }
        public int precio { get; set; }
        public int stock { get; set; }
        public int restriccion { get; set; }
    }
}
